### ISSUE TITLE
Code review #1

### ISSUE THREAD

**Issue by montomos** [rakuten-rex/checkbox#1]
Component
- [x] Rename existing Checkbox component to CheckboxUI
- [x] Create a new component Checkbox as a single dynamic checkbox
- [x] Fix CheckboxGroup logic to make dynamic knobs works.  (state and props are separeted)

**Comment by claudio-moya** [comment]
Component
- [ ] Left margin might be 0 instead of 0.5, confirm with design team

Stories
- [ ] CommonProps should be extracted as object:
```js
const { id, label, name } = CommonProps();
```
- [ ] Add `layout` option to CheckboxGroup in With Dynamic Props

**Comment by claudio-moya** [comment]
Component
- [ ] Animation for Check Icon looks funny
- [ ] In story http://localhost:8080/?path=/story/checkboxui-uncontrolled--default-view there is a warning
```js
Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
```

Stories
- [ ] Add Category `Checkbox Group / Controlled` to `Checkbox Group`
- [ ] Create `Default View` for `Checkbox Group`, same than `Layout Inline` but with default Checkbox  state

**Comment by claudio-moya** [comment]
Component
- [ ]  Check icon is bigger and with less margin than the Figma file
- [ ] Layout Block is not working  http://localhost:8080/?path=/story/checkbox-group-controlled--layout-block
- [ ] A new warning about defaultChecked is showed in all stories
```
Warning: A component contains an input of type checkbox with both checked and defaultChecked props. Input elements must be either controlled or uncontrolled (specify either the checked prop, or the defaultChecked prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components
```

**Comment by claudio-moya** [comment]
Component
- [ ] Add onChange function to checkbox based on warning at http://localhost:8080/?path=/story/checkboxui-uncontrolled--default-view
```js 
Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
```
