### ISSUE TITLE
BrowserStack QA

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/checkbox#5]
## Checkbox
- [x] Default
https://rakuten-rex.github.io/checkbox/iframe.html?id=checkbox-controlled--default-view&knob-Quantity%20of%20items=9&knob-layout%20(Block/Inline)=true&knob-id=dog&knob-name=pet&knob-label=Dog&knob-value=dog&knob-checked=true
- [x] Checked
https://rakuten-rex.github.io/checkbox/iframe.html?id=checkbox-controlled--checked-view&knob-Quantity%20of%20items=9&knob-layout%20(Block/Inline)=true&knob-id=dog&knob-name=pet&knob-label=Dog&knob-value=dog&knob-checked=true
- [x] Disabled
https://rakuten-rex.github.io/checkbox/iframe.html?id=checkbox-controlled--disabled-view&knob-Quantity%20of%20items=9&knob-layout%20(Block/Inline)=true&knob-id=dog&knob-name=pet&knob-label=Dog&knob-value=dog&knob-checked=true
- [x] Theme
https://rakuten-rex.github.io/checkbox/iframe.html?id=checkbox-controlled--with-theme-react-and-css-vars&knob-Quantity%20of%20items=9&knob-layout%20(Block/Inline)=true&knob-id=dog&knob-name=pet&knob-label=Dog&knob-value=dog&knob-checked=true

## Checkbox Group
- [x] Inline
https://rakuten-rex.github.io/checkbox/iframe.html?id=checkbox-group-controlled--layout-inline&knob-Quantity%20of%20items=9&knob-layout%20(Block/Inline)=true&knob-id=dog&knob-name=pet&knob-label=Dog&knob-value=dog&knob-checked=true
- [x] Block
https://rakuten-rex.github.io/checkbox/iframe.html?id=checkbox-group-controlled--layout-block&knob-Quantity%20of%20items=9&knob-layout%20(Block/Inline)=true&knob-id=dog&knob-name=pet&knob-label=Dog&knob-value=dog&knob-checked=true
- [x] Inline list
https://rakuten-rex.github.io/checkbox/iframe.html?id=checkbox-group-controlled--with-dynamic-props-group&knob-Quantity%20of%20items=9&knob-layout%20(Block/Inline)=true&knob-id=dog&knob-name=pet&knob-label=Dog&knob-value=dog&knob-checked=true
- [x] Block list
https://rakuten-rex.github.io/checkbox/iframe.html?id=checkbox-group-controlled--with-dynamic-props-group&knob-Quantity%20of%20items=9&knob-layout%20(Block/Inline)=true&knob-id=dog&knob-name=pet&knob-label=Dog&knob-value=dog&knob-checked=true 

## Devices list
![image](https://user-images.githubusercontent.com/10554673/75302073-18010680-5880-11ea-926a-5ab4600ab431.png)
![image](https://user-images.githubusercontent.com/10554673/75302080-1afbf700-5880-11ea-8b4d-59b406915d33.png)

![image](https://user-images.githubusercontent.com/10554673/75302062-0fa8cb80-5880-11ea-8f32-74ba6a3fe840.png)

**Comment by montomos** [comment]
**win10_ie_11 0**
Default 
- border-color is different
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75303433-0e799d80-5884-11ea-966d-161cc6fb0c4a.png)


Checked
- not checked
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75303274-9c08bd80-5883-11ea-8c1e-1071386907f3.png)
